project1/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from project1.project1.users import views as users

urlpatterns = [
    url(r'^$', users.home, name="home"),
    url(r'^admin/', admin.site.urls),
    # url(r'^drafts/$', profiles.profile_drafts, name='profile_drafts'),
    url(r'^posts/', include("project1.project1.posts.urls", namespace="posts")),
    url(r'^tags/', include("project1.project1.tags.urls", namespace="tags")),
    url(r'^users/', include("project1.project1.users.urls", namespace="users")),
    url(r'^sessions/', include("project1.project1.session.urls", namespace="sessions")),
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project1/session/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.session_list, name='session_list'),
    url(r'^new/$', views.session_create, name='session_create'),
]

project1/tags/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.tag_list, name='tag_list'),
    url(r'^(?P<pk>\d+)/$', views.tag_detail, name='tag_detail'),
    url(r'^demo/$', views.tag_demo, name='tag_demo'),

]

project1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>{% block title %}Viz{% endblock title %}</title>

  <!-- Bootstrap -->
  <!-- <link href="{% static "bootstrap-3.3.7-dist/bootstrap-3.3.7-dist/css/bootstrap.min.css" %}" rel="stylesheet"> -->
  <link href="{% static "bootstrap/css/bootstrap.css" %}" rel="stylesheet">
  <link href="{% static "font-awesome-4.7.0/font-awesome-4.7.0/css/font-awesome.css" %}" rel="stylesheet">
  <link href="{% static "css/index.css" %}" rel="stylesheet">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="{% block body-bg %}{% endblock body-bg %}">

  <div id="nav">
    <div class="container pt--m pb--m">
      <div class="flex flex--space-between">
        <a href="{% url 'home' %}"><img src="{% static "png/png/badoo.png" %}" class="img--logo" alt="Logo"></a>


          <ul class="list flex">
            <li class="mr--s"><a href="{% url 'tags:tag_list' %}" class="transparent pd--s">Tags</a></li>
            <li class="mr--s">
              <div class="input-wrapper">
                <input class="w--100p pd--xs bd" type="text" placeholder="Search">
              </div>
            </li>
            {% if request.user.is_authenticated %}
            <li class="rel">
              <button id="js-dropdown-toggle" class="button" >
                <img src="{{ request.user.profile.avatar.url }}" class="avatar--s">
              </button>
                <div id="js-dropdown" class="abs abs-r--zero card pt--s pb--s w--100 hidden">
                <ul class="list">
                  <li><a href="{% url 'posts:post_create' %}" class="block transparent  pd--s">New post</a></li>
                  <li><a href="{% url 'profile_drafts' %}" class="block transparent pd--s">Drafts</a></li>
                  <li><a href="{% url 'profiles:profile_detail' pk=request.user.pk %}" class="block transparent pd--s">Profile</a></li>
                  <li><a href="#" class="block transparent pd--s">Settings</a></li>
                  <li><button type="button" class="button w--100 transparent text-left" id="js-delete-session">Sign out</button></li>
                </ul>
                </div>
              <!-- </div> -->
            </li>
              {% else %}
              <li class="mr--s"><a href="{% url 'sessions:session_create' %}" class="transparent pd--s">Sign in</a></li>
              <li><a href="{% url 'users:user_create' %}" class="transparent pd--s">Sign up</a></li>
              {% endif %}
          </ul>

      </div>
    </div>
  </div>

  {% block body %}
  {% endblock body %}
  <div class="container pt--m pb--m">
    <ul id="footer" class="list">
      <li class="footer-li mb--m pb--m bb--light"><a href="#" class="transparent">Getting started</a></li>
      <li class="footer-li mb--m pb--m bb--light"><a href="#" class="transparent">Help</a></li>
      <li class="footer-li mb--m pb--m bb--light"><a href="#" class="transparent">Status</a></li>
      <li class="footer-li mb--m pb--m bb--light"><a href="#" class="transparent">Blog</a></li>
      <li class="footer-li mb--m pb--m bb--light"><a href="#" class="transparent">Careers</a></li>
      <li class="footer-li mb--m pb--m bb--light"><a href="#" class="transparent">Privacy</a></li>
      <li class="footer-li mb--m pb--m bb--light"><a href="#" class="transparent">Terms</a></li>
      <li id="footer-li--last" class="pb--m bb--light"><a href="#" class="transparent">About</a></li>
    </ul>
  </div>


  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="{% static "bootstrap-3.3.7-dist/bootstrap-3.3.7-dist/js/bootstrap.min.js" %}"></script>
  <!-- <script src="{% static "js/autosize.min.js" %}"></script> -->
  <script src="{% static "js/base.js" %}"></script>

  {% block js %}
  {% endblock js %}
</body>
</html>

project1/templates/draft_delete_modal.html
<div id="js-delete-modal" class="modal-wrapper hidden">
  <div class="modal pd--l">
    <button type="button" class="button button--modal transparent js-modal-close"><span class="fa fa-times" aria-hidden="true"></span></button>
    <div class="modal__header mb--m">
      <h3>Delete Draft?</h3>
    </div>
    <div class="modal__body mb--m">
      <p>Are you sure you want to delete this draft?</p>
    </div>
    <div class="modal__footer">
      <div class="flex flex--end">
        <button type="button" class="button transparent mr--s js-modal-close">Cancel</button>
        <button type="button" id="js-delete-draft" class="button button--primary transparent">Delete Draft</button>
      </div>
    </div>
  </div>
</div>

project1/templates/draft_publish_modal.html
<div id="js-publish-modal" class="modal-wrapper hidden">
  <div class="modal pd--l">
    <button type="button" class="button button--modal transparent js-modal-close"><span class="fa fa-times" aria-hidden="true"></span></button>
    <div class="modal__header mb--m">
      <h3>Publish Draft?</h3>
    </div>
    <div class="modal__body mb--m">
      <p>Are you sure you want to publish this draft?</p>
    </div>
    <div class="modal__footer">
      <div class="flex flex--end">
        <button type="button" class="button transparent mr--s js-modal-close">Cancel</button>
        <button type="button" id="js-publish-draft" class="button button--primary transparent">Publish Draft</button>
      </div>
    </div>
  </div>
</div>

project1/templates/login_modal.html
{% load widget_tweaks %}
<div class="modal-wrapper">
  <div class="modal">
    <button type="button" class="button button--modal transparent js-modal-close"><span class="fa fa-times" aria-hidden="true"></span></button>

    <div id="js-signup-tab">
        <h2 class="mb--m text-center">Join Viz today.</h2>
        <form class="mb--m" method="POST" action="/users/">
          {% csrf_token %}
          <div class="input-wrapper mb--s">
            <input id="id_username" class="pd--s w--100p" maxlength="150" name="username" type="text" required="" placeholder="Username">
          </div>
          <div class="input-wrapper mb--s">
            <input id="id_email" class="pd--s w--100p" maxlength="254" name="email" type="email" required="" placeholder="Email">
          </div>
          <div class="input-wrapper mb--s">
            <input id="id_password" class="pd--s w--100p" maxlength="128" name="password" type="password" required="" placeholder="Password">
          </div>
          <button type="submit" class="button button--primary w--100p transparent mb--s">Sign up</button>
          <p>By signing up, you agree to the <a href="#" class="transparent clr--primary">Terms of Service</a> and <a href="#" class="transparent clr--primary">Privacy Policy</a>, including <a href="#" class="transparent clr--primary">Cookie Use</a>. </p>
        </form>

      <div class="flex">
        <span class="mr--s">Have an account?</span>
        <button type="button" id="js-login-tab-toggle" class="button transparent pd-zero clr--primary">Log in</button>
      </div>
    </div>

    <div class="tab hidden" id="js-login-tab">
      <div class="mb--m">
          <h2 class="text-center">Log in To Viz</h2>
      </div>
      <div class="mb--m">
        <form method="post" action="/login/?next={{ url }}">
          {% csrf_token %}
          <div class="input-wrapper mb--s">
              {{ loginform.username|attr:"placeholder:Username"|add_class:"input" }}
          </div>
          <div class="input-wrapper mb--s">
              {{ loginform.password|attr:"placeholder:Password"|attr:"type:password"|add_class:"input" }}
          </div>
          <button type="submit" class="button button--block button--primary transparent">Log in</button>
        </form>
      </div>
      <div class="flex">
        <span class="mr--xs">New to Viz?</span>
        <button type="button" id="js-signup-tab-toggle" class="button transparent pd-zero clr--primary">Sign up</button>
      </div>
    </div>
  </div>
</div>


<div id="js-delete-modal" class="modal-wrapper hidden">
  <div class="modal pd--l">
    <button type="button" class="button button--modal transparent js-modal-close"><span class="fa fa-times" aria-hidden="true"></span></button>
    <div class="modal__header mb--m">
      <h3>Delete Post?</h3>
    </div>
    <div class="modal__body mb--m">
      <p>Are you sure you want to delete this post?</p>
    </div>
    <div class="modal__footer">
      <div class="flex flex--end">
        <button type="button" class="button transparent mr--s js-modal-close">Cancel</button>
        <button type="button" id="js-delete-post" class="button button--primary transparent">Delete Post</button>
      </div>
    </div>
  </div>
</div>

project1/templates/post_create.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block nav-v-tags %}
{% endblock nav-v-tags %}
{% block nav-tags %}
{% endblock nav-tags %}

{% block body %}
<div class="section">
  <div class="container">
    <div id="post-create" class="mg--center">
      <form method="POST" action="/posts/">
        {% csrf_token %}
          <div class="input-wrapper mb--m">
            {{ form.title|attr:"placeholder:Title"|attr:"id:js-input"|add_class:"input focus--disabled ft--32 pd--s bd"  }}
          </div>
          <div class="input-wrapper mb--m">
            {{ form.content|attr:"id:js-textarea" }}
          </div>
          <div class="flex">
            <button type="submit" name="draft" class="button button--primary mr--s js-submit">Save draft</button>
            <button type="submit" class="button button--primary js-submit">Publish</button>
          </div>
      </form>
    </div>
  </div>
</div>
{% endblock body %}

{% block js %}
<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
<script src="{% static "js/post_create.js" %}"></script>
{% endblock js %}

project1/templates/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}{{ post.title }}{% endblock title %}

{% block body %}
<div class="section">
  <div class="container">
    {% include "alert.html" %}
    <div class="flex">
        <a href="{{ post.user.profile.get_absolute_url }}" class="mr--s"><img src="{{ post.user.profile.avatar.url}}" class="avatar--s"></a>
        <a href="{{ post.user.profile.get_absolute_url }}">{{ post.user.username }}</a>
    </div>
    <div>
      {{ post.title }}
    </div>

    <div>
      {{ post.content }}
    </div>




  </div>
</div>
<div class="container">
  <div class="card">
    <div class="card__body">
      <div class="contentitem" data-url="{{ post.get_absolute_url }}" data-id="{{ post.id }}">
        <div class="contentitem-item">
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </div>
        <div class="contentitem-item contentitem-item-flex">
          <div class="avatar--small spaceright--large">
            <a class="avatar__action" href="{% url 'profiles:profile_activity' id=post.user.id slug=post.user.profile.slug %}"></a>
            <img class="img--cover imgborder--small" src="{{ post.user.profile.avatar.url }}">
          </div>
          <div>
            <div>
              <a href="{% url 'profiles:profile_activity' id=post.user.id slug=post.user.profile.slug %}">{{ post.user.username }}</a>
            </div>
            <div>
              {% if post.user.profile.credential %}<span>{{ post.user.profile.credential }}</span>{% endif %}
            </div>
          </div>
        </div>
        <div class="contentitem-item">
          <div>{{ post.content }}</div>
        </div>
        <div class="contentitem-item">
          <a href="{{ post.topic.get_absolute_url }}">{{ post.topic }}</a>
        </div>
        <div class="contentitem-item">
          <a href="{{ post.get_absolute_url }}">Published {{ post.date_published }}</a>
        </div>
        <div class="contentitem-item">
          <button type="button" class="button button--blue {% if liked_post %}button--active{% endif %} {% if not request.user.is_authenticated %}js-get-login-modal{% endif %} {% if request.user.is_authenticated and request.user != user %}js-post-like{% endif %}" {% if request.user == user %}disabled{% endif %}><span class="fa fa-thumbs-o-up spaceright--small" aria-hidden="true"></span><span>{{ post.likes }}<span></button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

{% block javascript %}
<script src="{% static "js/post_detail.js" %}"></script>
{% endblock javascript %}

project1/templates/post_detail_partial.html
{% load static %}
{% load widget_tweaks %}
<div class="section post_detail_page"" id="post_detail_page_{{comments_current_page.number}}" data-pagenum={{comments_current_page.number}}>


<div class="page-header" id="post_detail_page_header">
  <h4 id="comments_count">{{ comments_count }} {{comment_title}}</h4>
</div>

{% if no_comments %}
<div id="no_comments">
  <p>There are no comments.</p>
</div>
{% endif %}

<div class="media" id='comment_form_container'>
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="/media/profile_avatar/1.jpg" alt="..." width="64px" height="64px">
    </a>
  </div>
  <div class="media-body">
    <form method="post" id="comment_form">
      {% csrf_token %}

      {% if form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {{ form.non_field_errors }}
      </div>
      {% endif %}

      <!-- Button trigger modal -->
      <div class="form-group" >
        <textarea class="form-control" id="comment_form_textfield" rows="3" placeholder="Leave a commment." required></textarea>

        {% if form.content.errors %}
        <div class="alert alert-danger" role="alert">
          {{ form.content.errors }}
        </div>
        {% endif %}
        {% if form.content.help_text %}
        <p class="help-block">{{ form.content.help_text|safe }}</p>
        {% endif %}
      </div>


      <div class="collapse" id="collapseExample">
        <button type="submit" class="btn btn-primary" >{{ comment_button_text }}</button>
      </div>



    </form>
  </div>
</div>

{% if no_comments == False %}
<div id='post_detail_comment_list'>
  {% for comment in comments_current_page %}
  <div class="media">
    <div class="media-left">
      <a href="{% url 'profiles:profile_activity' id=comment.user.id slug=comment.user.profile.slug %}">
        <img class="media-object" src="{{ comment.user.profile.avatar.url }}" alt="..." width="64px" height="64px">
      </a>
    </div>
    <div class="media-body">
      <a class="media-heading" href="{% url 'profiles:profile_activity' id=comment.user.id slug=comment.user.profile.slug %}">{{ comment.user.username }}</a>
      <p>{{ comment.content}} </p>
      <p>{{ comment.date_created}} </p>
    </div>
  </div>
  {% endfor %}
</div>

<div id="post_detail_pag">
  <ul id="post_detail_pag_ul" class="pagination">
    {% if comments_current_page.has_previous %}
    <li><a class="page_button" href="?page={{ comments_current_page.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in comments_current_page.paginator.page_range %}
    {% if comments_current_page.number == i %}
    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
    <li><a class="page_button" href="?page={{ i }}" >{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if comments_current_page.has_next %}
    <li><a class="page_button" href="?page={{ comments_current_page.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
</div>
{% endif %}
</div>

project1/templates/post_update.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}update post{% endblock title %}

{% block body %}

<!-- <form method="post">{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='Update Post'>
</form> -->

<!-- {% if messages %}
<section >
  <div class='container'>
    <div class='row'>

      <div class="alert alert-success" role="alert">
        <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>

      </div>
    </div>
  </div>
</section>
{% endif %} -->

<section >
  <div class='container'>
    <div class='row'>

      <div class='col-lg-6 col-md-offset-3'>
        {% if messages %}
        <div class="alert alert-success" role="alert">
          <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
        </div>
        {% endif %}
        <h2>{{ title }}</h2>
        <form method="post">
          {% csrf_token %}

          {% if form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            {{ form.non_field_errors }}
          </div>
          {% endif %}

          <div class="form-group">
            {{ form.title|add_class:"form-control"|attr:"autofocus"|attr:"placeholder:Title" }}
            {% if form.title.errors %}
            <div class="alert alert-danger" role="alert">
              {{ form.title.errors }}
            </div>
            {% endif %}
            {% if form.title.help_text %}
            <p class="help-block">{{ form.title.help_text|safe }}</p>
            {% endif %}
          </div>

          <div class="form-group">
            {{ form.content|add_class:"form-control"|attr:"placeholder:Content" }}
            {% if form.content.errors %}
            <div class="alert alert-danger" role="alert">
              {{ form.content.errors }}
            </div>
            {% endif %}
            {% if form.content.help_text %}
            <p class="help-block">{{ form.content.help_text|safe }}</p>
            {% endif %}
          </div>

          <div class="form-group">
            {{ form.category|add_class:"form-control"|attr:"placeholder:Content" }}
            {% if form.category.errors %}
            <div class="alert alert-danger" role="alert">
              {{ form.category.errors }}
            </div>
            {% endif %}
            {% if form.category.help_text %}
            <p class="help-block">{{ form.category.help_text|safe }}</p>
            {% endif %}
          </div>





          <button type="submit" class="btn btn-primary">{{ button_text }}</button>
        </form>
      </div>

    </div>
  </div>
</section>
{% endblock body %}

project1/templates/profile_avatar_modal.html
<div id="js-avatar-modal" class="modal-wrapper hidden">
  <div class="modal pd--l">
    <button type="button" id="js-avatar-modal-close" class="button button--modal transparent"><span class="fa fa-times" aria-hidden="true"></span></button>
    <div class="modal__header text-center mb--l">
      <h3>Edit Avatar</h3>
    </div>
    <div class="modal__body mb--l flex flex--center">
      <canvas id="js-avatar-canvas" width="200" height="200"></canvas>
    </div>
    <div class="modal__footer flex flex--center">
      <!-- <div class="flex flex--end">
        <button type="button" class="button transparent mr--s js-avatar-modal-close">Cancel</button> -->
        <button type="button" id="js-edit-avatar" class="button button--primary transparent">Edit</button>
      <!-- </div> -->
    </div>
  </div>
</div>

project1/templates/profile_base.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block nav-v-tags %}
{% endblock nav-v-tags %}
{% block nav-tags %}
{% endblock nav-tags %}

{% block body-bg %}bg--gray{% endblock body-bg %}

{% block body %}
{% include "alert.html" %}
<div class="pt--m pb--m">
  <div class="container">
    <div id="profile" class="card pd--m">
      <div id="profile-bg" class="mt-neg--m ml-neg--m mr-neg--m" style="background:url({{ profile.background.url }}) no-repeat center;background-size:cover">
      </div>
      <div id="profile-info" class="rel">
        <div id="avatar-wrapper">
          <img id="avatar" src="{{ profile.avatar.url }}">
        </div>
        <div class="rel">
          {% if profile.user == request.user %}
          <a href="{{ profile.get_edit_url }}" class="a--primary transparent abs abs-r--zero abs-b--zero">Edit</a>
          {% endif %}

          <h1 id="profile-username" class="text-center mb--s">{{ profile.user.username }}</h1>
          {% if profile.credential %}
          <div id="profile-credential" class="text-center mb--s">
            <span>{{ profile.credential }}</span>
          </div>
          {% endif %}
          {% if profile.description %}
          <div id="profile-description" class="text-center mb--s">
            <span>{{ profile.description }}</span>
          </div>
          {% endif %}
          {% if profile.gender %}
          <div class="flex mb--s">
            <span class="mr--s bold w--100">Gender</span>
            <span>{{ profile.gender }}</span>
          </div>
          {% endif %}
          {% if profile.industry %}
          <div class="flex mb--s">
            <span class="mr--s bold w--100">Industry</span>
            <span>{{ profile.industry }}</span>
          </div>
          {% endif %}
          {% if profile.position %}
          <div class="flex mb--s">
            <span class="mr--s bold w--100">Position</span>
            <span>{{ profile.position }}</span>
          </div>
          {% endif %}
          {% if profile.company %}
          <div class="flex mb--s">
            <span class="mr--s bold w--100">Company</span>
            <span>{{ profile.company }}</span>
          </div>
          {% endif %}
          {% if profile.school %}
          <div class="flex mb--s">
            <span class="mr--s bold w--100">School</span>
            <span>{{ profile.school }}</span>
          </div>
          {% endif %}
          {% if profile.concentration %}
          <div class="flex mb--s">
            <span class="mr--s bold w--100">Concentration</span>
            <span>{{ profile.concentration }}</span>
          </div>
          {% endif %}
          {% if profile.location %}
          <div class="flex">
            <span class="mr--s bold w--100">Location</span>
            <span>{{ profile.location }}</span>
          </div>
          {% endif %}


        </div>
      </div>
    </div>
  </div>
</div>

<div class="pb--m">
  <div class="container">
    <div class="row">
      <div class="col-md-2 mb--m">
        <div class="card pd--m">
          <h3 class="mb--m pb--m bb--light">Feeds</h3>
          <ul class="list ml-neg--m mr-neg--m">
            <li><a href="{% url 'profiles:profile_posts' pk=profile.pk %}" class="block pd--m transparent {% block profile-posts %}{% endblock profile-posts %}">Posts</a></li>
            <li><a href="{% url 'profiles:profile_followers' pk=profile.pk %}" class="block pd--m transparent {% block profile-followers-active %}{% endblock profile-followers-active %}">Followers</a></li>
            <li><a href="{% url 'profiles:profile_following' pk=profile.pk %}" class="block pd--m transparent {% block profile-following-active %}{% endblock profile-following-active %}">Following</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-10">
        <div class="card pd--m">
          {% block profile-content %}
          {% endblock profile-content %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

{% block js %}
<script src="{% static "js/profile_base.js" %}"></script>
{% endblock js %}

project1/templates/profile_drafts.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block nav-v-tags %}
{% endblock nav-v-tags %}
{% block nav-tags %}
{% endblock nav-tags %}

{% block body %}
<div class="section">
  <div class="container">
    <div id="js-target" class="pd--m">
      {% include "alert.html" %}
      <h3 class="mb--m pb--m bb--light">{{ drafts_count }} Drafts</h3>
      {% if drafts %}
      <div class="mb--m">
        {% for post in drafts %}
        <div class="post {% if not forloop.last %}mb--m{% endif %} pb--m bb--light">
          <h3 class="mb--s"><a href="{{ post.get_edit_url }}">{{ post.title }}</a></h3>
          <ul class="list flex">
            <li class="mr--s"><span>{{ post.date_updated }}</span></li>
            <li class="mr--s"><a href="{{ post.get_edit_url }}" class="transparent">Edit</a></li>
            <li class="mr--s"><button type="button" class="button transparent pd-zero js-delete" data-url="{{ post.get_absolute_url }}">Delete</button></li>
            <li><button type="button" class="button transparent pd-zero js-publish" data-url="{{ post.get_absolute_url }}">Publish</button></li>
          </ul>
        </div>
        {% endfor %}
      </div>

      <ul class="pagination list flex flex--center">
        {% if drafts.has_previous %}
        <li class="mr--s pd--s"><a href="?page={{ drafts.previous_page_number }}" class="transparent"><span class="fa fa-angle-double-left" aria-hidden="true"></span></a></li>
        {% endif %}
        {% for i in drafts.paginator.page_range %}
        {% if drafts.number == i %}
        <li class="mr--s pd--s"><span >{{ i }}</span></li>
        {% else %}
        <li class="mr--s pd--s"><a href="?page={{ i }}" class="transparent">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if drafts.has_next %}
        <li class="pd--s"><a href="?page={{ drafts.next_page_number }}" class="transparent"><span class="fa fa-angle-double-right" aria-hidden="true"></span></a></li>
        {% endif %}
      </ul>
      {% else %}
      <h3>You have zero drafts.</h3>
      {% endif %}
    </div>
  </div>
</div>
{% endblock body %}

{% block js %}
{% include "draft_delete_modal.html" %}
{% include "draft_publish_modal.html" %}
<script src="{% static "js/profile_drafts.js" %}"></script>
{% endblock js %}

project1/templates/session_create.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block body %}
  <div class="container pt--m pb--m">
    <div id="session-create-form">
    <h3 class="mb--m text-center">Sign in to Viz.</h3>
      <form method="POST" action="/sessions/">
        {% csrf_token %}


          <div class="input-wrapper mb--m">
            {{ form.username|attr:"placeholder:Username"|add_class:"pd--s w--100p" }}
          </div>
          <div class="input-wrapper mb--m">
            {{ form.password|attr:"placeholder:Password"|attr:"type:password"|add_class:"pd--s w--100p" }}
          </div>
          {% if form.non_field_errors %}
          <ul class="list mb--m">
          {% for error in form.non_field_errors %}
          <li class="text-center cr--red">{{ error }}</li>
          {% endfor %}
          </ul>
          {% endif %}
          <button type="submit" class="button button--primary w--100p transparent js-submit">Sign in</button>
      </form>
    </div>
  </div>
{% endblock body %}

project1/templates/tag_demo.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}


{% block body %}
<form>
  {{ form}}
</form>

{% endblock body %}